version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-server
    restart: unless-stopped
    user: "0:0"  # Запуск от имени root
    environment:
      - EULA=true
      - VERSION=1.20.1
      - MEMORY=512m
      - TYPE=FORGE
      - FORGEVERSION=47.2.0
      - MCVERSION=1.20.1
    volumes:
      - ./data:/data
      - ./eula.txt:/data/eula.txt
    ports:
      - "25565:25565"
    networks:
      - minecraft-network

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: minecraft-proxy
    restart: unless-stopped
    ports:
      - "25566:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-proxy-protocol.conf:/etc/nginx/conf.d/stream.conf
      - ./nginx-http.conf:/etc/nginx/conf.d/http.conf
    tmpfs:
      - /tmp
    depends_on:
      - minecraft
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge

volumes:
  minecraft-data:
    driver: local